return {
  {
    "folke/lazydev.nvim",
    ft = "lua",
    opts = { library = { { path = "luvit-meta/library", words = { "vim%.uv" } } } },
  },
  -- Useful status updates for LSP.
  -- NOTE: `opts = {}` is the same as calling `require('fidget').setup({})`
  { "j-hui/fidget.nvim", opts = {} },
  -- Allows extra capabilities provided by nvim-cmp
  "hrsh7th/cmp-nvim-lsp",
  -- {
  --   "neovim/nvim-lspconfig",
  --   dependencies = {
  --     -- Automatically install LSPs and related tools to stdpath for Neovim
  --
  --   },
  --   config = function()
  --     vim.api.nvim_create_autocmd("LspAttach", {
  --       group = vim.api.nvim_create_augroup("lsp-attach", { clear = true }),
  --       callback = function(event)
  --         local map = function(keys, func, desc, mode)
  --           vim.keymap.set(mode or "n", keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
  --         end
  --
  --         local telescope = require("telescope.builtin")
  --         -- jump to definition.. to go back, press <C-t>
  --         map("gd", telescope.lsp_definitions, "Goto Definition")
  --         map("gr", telescope.lsp_references, "Goto References")
  --         map("gI", telescope.lsp_implementations, "Goto Implementation")
  --         map("<leader>D", telescope.lsp_type_definitions, "Type Definition")
  --         map("<leader>ds", telescope.lsp_document_symbols, "Document Symbols")
  --         map("<leader>rn", vim.lsp.buf.rename, "Rename")
  --         map("<leader>ca", vim.lsp.buf.code_action, "Code Action", { "n", "x" })
  --         map("gD", vim.lsp.buf.declaration, "Goto Declaration")
  --
  --         -- The following two autocommands are used to highlight references of the
  --         -- word under your cursor when your cursor rests there for a little while.
  --         --    See `:help CursorHold` for information about when this is executed
  --         --
  --         -- When you move your cursor, the highlights will be cleared (the second autocommand).
  --         local client = vim.lsp.get_client_by_id(event.data.client_id)
  --         if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_documentHighlight) then
  --           local highlight_augroup = vim.api.nvim_create_augroup("lsp-highlight", { clear = false })
  --           vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI" }, {
  --             buffer = event.buf,
  --             group = highlight_augroup,
  --             callback = vim.lsp.buf.document_highlight,
  --           })
  --
  --           vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
  --             buffer = event.buf,
  --             group = highlight_augroup,
  --             callback = vim.lsp.buf.clear_references,
  --           })
  --
  --           vim.api.nvim_create_autocmd("LspDetach", {
  --             group = vim.api.nvim_create_augroup("lsp-detach", { clear = true }),
  --             callback = function(event2)
  --               vim.lsp.buf.clear_references()
  --               vim.api.nvim_clear_autocmds({ group = "lsp-highlight", buffer = event2.buf })
  --             end,
  --           })
  --         end
  --
  --         if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint) then
  --           map(
  --             "<leader>th",
  --             function() vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = event.buf })) end,
  --             "Toggle Inlay Hints"
  --           )
  --         end
  --       end,
  --     })
  --
  --     local capabilities = vim.lsp.protocol.make_client_capabilities()
  --     capabilities = vim.tbl_deep_extend("force", capabilities, require("cmp_nvim_lsp").default_capabilities())
  --
  --     vim.lsp.config["rust_analyzer"] = {
  --       cmd = { "rust-analyzer" },
  --       filetypes = { "rust" },
  --       root_markers = { ".git", "Cargo.toml" },
  --       settings = {
  --         ["rust-analyzer"] = {
  --           check = { command = "clippy", extraArgs = { "--tests" } },
  --           -- cargo = { features = "all" },
  --           rustfmt = { extraArgs = { "+nightly" } },
  --         },
  --       },
  --     }
  --
  --     vim.lsp.enable("rust_analyzer")
  --   end,
  -- },
}
